all: analyze analyze2 generate generate2

analyze: analyze.c makefile
	gcc -Wall -Os analyze.c -lm -o analyze

analyze2: analyze2.c makefile
	gcc -Wall -Os analyze2.c -lm -o analyze2

generate: generate.c makefile
	gcc -Wall -Os generate.c -lm -o generate

generate2: generate2.c makefile
	gcc -Wall -Os generate2.c -o generate2
